version: 2.1

executors:
  default:
    docker:
      - image: circleci/php:8.1.23

jobs:
  build:
    executor: default
    steps:
      - checkout  # リポジトリのコードをチェックアウト
      - run:
          name: Install PHP Dependencies
          command: |
            composer install --ignore-platform-reqs  # Laravelプロジェクトの依存関係をインストール（PHPのバージョン要求を無視）
      - run:
          name: Install Node.js Dependencies
          command: |
            npm install  # Laravelのフロントエンド依存関係をインストール
      - run:
          name: Build Assets
          command: |
            npm run production  # フロントエンドアセットのビルド
      - run:
          name: Database Migrations
          command: |
            php artisan migrate --force  # データベースマイグレーション

      # ここからデプロイステップ
      - run:
          name: Deploy to EC2
          command: |
            # EC2サーバーにSSHキーで接続し、コードをpull
            ssh -i ~/.ssh/ec2-ssh-key.pem ec2-user@your-ec2-instance-ip "cd /path/to/your/laravel/app && git pull origin master"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # masterブランチに変更がマージされたときのみ実行
